spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toyDB
    username: root
    password: 9826

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  sql:
    init:
      mode: always

  thymeleaf:
    prefix: classpath:templates/thymeleaf
    suffix: .html
    cache: false
    check-template-location: true

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace
  org.hibernate.orm.jdbc.bind: trace